// 知识小卡片 —— 双语术语表。课程正文里出现这些关键概念时，渲染器会自动给它加一条
// 虚线下划线，鼠标 hover / 键盘聚焦即弹出释义卡。每个条目：{ zh:{n:[匹配词…], d:释义 }, en:{…} }。
// n[0] 为卡片标题（规范写法），其余为别名/同义词；ASCII 词按词边界大小写精确匹配，中文按子串匹配。
// 所以：ASCII 的单复数/变形要各写一条（price 与 prices 不互相匹配）；中文别名务必够长够专——
// “价值”“市场”“利率”这类通用词会在全文乱开花，宁可写“主观价值”“市场过程”“自然利率”。同一概念每块正文只标注首次出现处。
// 释义一句话讲透，贴课程主线：价值是主观的，行动有目的，价格传递知识，时间与不确定性无法消去。
// 加词只改这个文件 + bump glossary.js?v 与 app.js?v，不动任何课文。

export const GLOSSARY = [
  // —— 价值与价格 ——
  { zh:{n:["主观价值","价值的主观性"],d:"价值不是物品的属性，而是行动人对物品能满足其目的的程度所做的评价——同一杯水，沙漠里和河边的价值天差地别。"},
    en:{n:["subjective value","subjective theory of value","value subjectivism"],d:"Value is not a property of things but a judgment by an acting person about how well a thing serves their ends — the same glass of water is worth wildly different amounts in a desert and by a river."} },
  { zh:{n:["边际效用"],d:"再多一单位某物所能满足的最不迫切的那个需求的重要性——单位越多，每增一单位排到的用途越次要，所以边际效用递减。"},
    en:{n:["marginal utility"],d:"The importance of the least urgent want an additional unit of a good can satisfy. More units means each extra unit goes to a lower-ranked use — hence diminishing marginal utility."} },
  { zh:{n:["边际效用递减","边际效用递减律"],d:"同一物品拥有的单位越多，每多一单位被分配到的用途就越不重要，所以其价值越低——这是从行动公理推出的，不是心理学假设。"},
    en:{n:["diminishing marginal utility","law of diminishing marginal utility"],d:"The more units of a good you hold, the less important the use the next unit serves, so its value falls — derived from the logic of action, not assumed as psychology."} },
  { zh:{n:["边际革命"],d:"1871 年前后杰文斯、门格尔、瓦尔拉斯各自独立提出：价值由边际单位的效用决定，而非劳动或总效用——这一步解开了钻石与水的悖论。"},
    en:{n:["marginal revolution","Marginal Revolution"],d:"Around 1871, Jevons, Menger and Walras independently argued value is set by the utility of the marginal unit, not by labor or total usefulness — dissolving the diamond–water paradox."} },
  { zh:{n:["边际对"],d:"庞巴维克的定价法：市场价被夹在“最后一对成交的买卖双方”与“第一对没成交的买卖双方”的估值之间——价格由边际的四个人划定区间。"},
    en:{n:["marginal pairs","marginal pair"],d:"Böhm-Bawerk's price-formation device: the market price sits between the valuations of the last buyer-seller pair that trades and the first pair that doesn't — four marginal people bracket the price."} },
  { zh:{n:["机会成本"],d:"做一件事的真实成本是你为此放弃的最有价值的替代选择——成本永远是主观的、向前看的，不是账本上的历史支出。"},
    en:{n:["opportunity cost"],d:"The true cost of an action is the most valuable alternative you give up for it — cost is always subjective and forward-looking, never a historical entry in a ledger."} },
  { zh:{n:["价格信号"],d:"价格把分散在无数人头脑里的知识压缩成一个数字，告诉所有人“这东西现在有多稀缺”，无需任何人理解全局。"},
    en:{n:["price signal","price signals"],d:"A price compresses knowledge scattered across countless minds into one number telling everyone how scarce something is right now — without anyone needing to understand the whole picture."} },
  { zh:{n:["消费者主权"],d:"在自由市场里，最终决定生产什么的是消费者的买与不买——企业家再大也只是替消费者跑腿的“船长”，船的方向由乘客决定。"},
    en:{n:["consumer sovereignty"],d:"In a free market, what gets produced is ultimately decided by consumers buying or not buying — even the biggest entrepreneur is a captain whose course is set by the passengers."} },
  { zh:{n:["比较优势"],d:"即使你做每件事都比别人强，专注于你相对最擅长的事、把其余交换给别人，双方总产出仍会更高——米塞斯称之为“联合法则”。"},
    en:{n:["comparative advantage","law of association"],d:"Even if you are better at everything, specializing where your relative edge is greatest and trading for the rest raises total output for both sides — Mises called it the law of association."} },

  // —— 方法论 ——
  { zh:{n:["人的行动学","行动学"],d:"米塞斯给经济学方法起的名字：从“人有目的地行动”这一不可否认的公理出发，用逻辑演绎推出经济规律，而不是靠统计归纳。"},
    en:{n:["praxeology","praxeological"],d:"Mises's name for the method of economics: deduce economic laws logically from the undeniable axiom that humans act purposefully, rather than induce them from statistics."} },
  { zh:{n:["行动公理"],d:"“人有目的地行动”——你无法否认它而不自相矛盾，因为否认本身就是一个有目的的行动。奥派整座理论大厦的地基。"},
    en:{n:["action axiom"],d:"“Humans act purposefully” — you cannot deny it without contradiction, because denying it is itself a purposeful act. The foundation stone of the whole Austrian edifice."} },
  { zh:{n:["方法论个人主义"],d:"只有个人才会行动、选择、评价——“国家”“阶级”“市场”都不会。解释任何社会现象，最终必须落到具体的人的行动上。"},
    en:{n:["methodological individualism"],d:"Only individuals act, choose and value — “the state,” “the class,” “the market” do not. Any social phenomenon must ultimately be explained through the actions of particular people."} },
  { zh:{n:["先验"],d:"不依赖经验观察就能知道为真的命题，如“交换双方都预期获益”。奥派认为经济学核心定律属于此类，所以统计既不能证实也不能证伪它们。"},
    en:{n:["a priori"],d:"A proposition known true without empirical observation, e.g. “both parties to an exchange expect to gain.” Austrians hold core economic laws are of this kind, so statistics can neither confirm nor refute them."} },
  { zh:{n:["方法论二元论"],d:"米塞斯的主张：自然科学研究没有目的的物质，社会科学研究有目的的人——两者需要根本不同的方法，把物理学方法搬进经济学是范畴错误。"},
    en:{n:["methodological dualism"],d:"Mises's position: natural science studies purposeless matter, social science studies purposeful people — they need fundamentally different methods, and importing physics into economics is a category error."} },
  { zh:{n:["理解","Verstehen"],d:"韦伯与米塞斯的概念：解释历史事件时，学者要“理解”当事人的目的与信念——这不是理论，是把理论应用到具体案例的技艺。"},
    en:{n:["Verstehen","thymology"],d:"Weber's and Mises's notion: explaining a historical event requires understanding the purposes and beliefs of the actors — not theory itself but the craft of applying theory to a particular case."} },
  { zh:{n:["均衡","一般均衡"],d:"主流经济学的核心假想：所有市场同时出清、无人想改变行为的静止状态。奥派视之为思维工具而非现实——真实市场永远在“趋向”而从不“到达”。"},
    en:{n:["general equilibrium","equilibrium"],d:"Mainstream economics' central construct: a resting state where every market clears and nobody wants to change. Austrians treat it as a thought tool, not a description — real markets always tend toward it and never arrive."} },
  { zh:{n:["均匀轮转经济","ERE"],d:"米塞斯的思维实验：一个没有变化、没有不确定性、每天重复的经济体——它的用途只有一个：反衬出企业家利润在真实世界里从哪里来。"},
    en:{n:["evenly rotating economy","ERE"],d:"Mises's thought experiment: an economy with no change and no uncertainty, repeating identically every day — useful for exactly one thing: showing by contrast where entrepreneurial profit comes from in the real world."} },
  { zh:{n:["唯科学主义","科学主义"],d:"哈耶克的批评：不加反思地把自然科学的方法（测量、统计、预测）套到社会研究上，误把“看起来科学”当成真正的科学。"},
    en:{n:["scientism"],d:"Hayek's critique: uncritically copying the methods of natural science (measurement, statistics, prediction) into social study, mistaking the look of science for science itself."} },

  // —— 资本、时间与利息 ——
  { zh:{n:["时间偏好"],d:"其他条件相同，人总是偏好现在的满足胜过未来的同样满足——利息就是这种偏好的市场价格，不是资本“生产力”的回报。"},
    en:{n:["time preference"],d:"Other things equal, people prefer satisfaction now over the same satisfaction later — interest is the market price of this preference, not a reward for capital's “productivity.”"} },
  { zh:{n:["自然利率"],d:"维克塞尔的概念：在没有信用扩张的情况下，储蓄者的时间偏好与借款者的需求相遇形成的利率——央行把市场利率压到它之下，周期就开始。"},
    en:{n:["natural rate of interest","natural rate"],d:"Wicksell's term: the rate at which savers' time preference meets borrowers' demand absent credit expansion — when the central bank pushes the market rate below it, the cycle begins."} },
  { zh:{n:["迂回生产"],d:"庞巴维克的洞见：先造工具再用工具生产，比直接徒手生产更费时间但产出更多——文明的进步就是生产链条越拉越长。"},
    en:{n:["roundabout production","roundaboutness"],d:"Böhm-Bawerk's insight: building tools first and producing with them takes longer than producing bare-handed but yields far more — civilization advances by lengthening its chains of production."} },
  { zh:{n:["生产结构"],d:"从最上游的原材料到最下游的消费品，社会全部生产按“离消费多远”排成的阶段序列——奥派宏观分析的基本对象，主流总量模型把它压扁成了一个数。"},
    en:{n:["structure of production","stages of production"],d:"All of society's production arranged in stages by distance from the final consumer, from raw materials to retail — the basic object of Austrian macro, which mainstream aggregates flatten into a single number."} },
  { zh:{n:["哈耶克三角"],d:"一个直角三角形：横边是生产所需时间（阶段数），竖边是消费品价值——储蓄增加把三角拉长变扁，信用扩张则让两头同时膨胀直到断裂。"},
    en:{n:["Hayekian triangle","Hayek's triangle"],d:"A right triangle: the base is production time (number of stages), the height is consumer-goods value — more saving stretches it longer and flatter; credit expansion inflates both ends until it snaps."} },
  { zh:{n:["异质资本","资本异质性"],d:"资本品不是一团可随意变形的橡皮泥：一台印钞机改不成拖拉机。每件资本品只有有限的用途，所以“错误投资”是真损失，不是账面数字。"},
    en:{n:["heterogeneous capital","capital heterogeneity"],d:"Capital goods are not a lump of putty: a printing press cannot be reshaped into a tractor. Each has limited alternative uses, so malinvestment is a real loss, not a bookkeeping entry."} },
  { zh:{n:["资本消耗"],d:"当社会消费超过它维持资本存量所需的补偿投资时，机器折旧无人更换、库存耗尽无人补货——GDP 可能还在涨，但未来正被吃掉。"},
    en:{n:["capital consumption"],d:"When a society consumes more than what maintaining its capital stock requires, machines depreciate unreplaced and inventories drain — GDP can still rise while the future is being eaten."} },

  // —— 货币 ——
  { zh:{n:["回归定理"],d:"米塞斯 1912 年的证明：今天人们对货币的需求基于昨天的购买力，昨天基于前天……一直回溯到该物还只是普通商品的那一刻——货币必须起源于市场。"},
    en:{n:["regression theorem"],d:"Mises's 1912 proof: today's demand for money rests on yesterday's purchasing power, yesterday's on the day before's … back to when the thing was merely a commodity — so money must originate in the market."} },
  { zh:{n:["可销售性"],d:"门格尔的关键词：一件商品能多容易、以多小的折价卖出。可销售性最高的商品会被越来越多人拿来当交换媒介，最终演化成货币。"},
    en:{n:["saleableness","marketability","salability"],d:"Menger's key term: how easily and with how little discount a good can be sold. The most saleable good gets adopted as a medium of exchange by more and more people until it becomes money."} },
  { zh:{n:["交换媒介"],d:"你接受它不是为了自己用，而是为了再换别的东西——这是货币的定义性功能，“价值储藏”“记账单位”都是它的衍生。"},
    en:{n:["medium of exchange"],d:"Something you accept not to use but to trade on for something else — the defining function of money; “store of value” and “unit of account” derive from it."} },
  { zh:{n:["坎蒂隆效应"],d:"新钱不是均匀撒向所有人：先拿到的人（银行、政府、资产持有者）按旧价格花，后拿到的人（工薪、储户）只能面对涨过的价格——通胀是一场再分配。"},
    en:{n:["Cantillon effect","Cantillon effects"],d:"New money does not rain evenly: those who get it first (banks, governments, asset holders) spend at old prices; those who get it last (wage earners, savers) face already-risen prices — inflation is a redistribution."} },
  { zh:{n:["货币非中性"],d:"增加货币供给不会等比例抬高所有价格，而是沿着新钱流入的路径扭曲相对价格与生产结构——这是奥派与货币主义的根本分歧。"},
    en:{n:["non-neutrality of money","money is not neutral"],d:"Adding money does not lift all prices proportionally; it distorts relative prices and the production structure along the path the new money travels — the core split between Austrians and monetarists."} },
  { zh:{n:["部分准备金"],d:"银行只留存款的一小部分做准备金，其余贷出——每一笔贷款都创造了不由储蓄支撑的新货币，奥派认为这是周期的引擎。"},
    en:{n:["fractional reserve","fractional-reserve banking","fractional reserve banking"],d:"Banks keep only a fraction of deposits as reserves and lend out the rest — every such loan creates new money backed by no saving, which Austrians see as the engine of the cycle."} },
  { zh:{n:["信用扩张"],d:"银行体系在没有新增真实储蓄的情况下增加贷款——表现为利率被压低、货币供给上升，是奥派商业周期理论的起点。"},
    en:{n:["credit expansion"],d:"The banking system increasing loans without any new real saving behind them — showing up as a depressed interest rate and a rising money supply; the starting point of Austrian cycle theory."} },
  { zh:{n:["法币","法定货币"],d:"靠法律强制流通、没有商品背书的货币。1971 年美元与黄金脱钩后，全世界首次进入纯法币时代。"},
    en:{n:["fiat money","fiat currency","fiat"],d:"Money that circulates by legal decree with no commodity backing. After the dollar left gold in 1971 the whole world entered a pure-fiat era for the first time."} },
  { zh:{n:["金本位"],d:"货币单位定义为固定重量的黄金、可自由兑换的制度——它限制政府印钞的能力，这既是奥派推崇它的理由，也是政府抛弃它的理由。"},
    en:{n:["gold standard"],d:"A system where the monetary unit is a fixed weight of gold, freely convertible — it limits the state's ability to print, which is both why Austrians admire it and why states abandoned it."} },
  { zh:{n:["恶性通货膨胀","恶性通胀"],d:"货币购买力崩溃式下跌，人们争先恐后把钱换成任何实物——米塞斯称之为“崩溃繁荣”，是货币需求彻底消失的终点。"},
    en:{n:["hyperinflation"],d:"A collapse of purchasing power where people race to swap money for anything real — Mises's “crack-up boom,” the endpoint where demand for money vanishes altogether."} },
  { zh:{n:["硬通货","硬钱"],d:"供给难以扩张的货币（黄金、比特币）：谁都无法靠多印它来把财富转移给自己。"},
    en:{n:["hard money","sound money"],d:"Money whose supply is hard to expand (gold, Bitcoin): nobody can transfer wealth to themselves by printing more of it."} },

  // —— 商业周期 ——
  { zh:{n:["奥地利学派商业周期理论","ABCT","商业周期理论"],d:"米塞斯–哈耶克的理论：央行/银行压低利率→企业家误以为储蓄增加→上游过度投资→资源不够完成所有项目→清算。繁荣是病，萧条是治。"},
    en:{n:["Austrian business cycle theory","ABCT","Austrian Business Cycle Theory"],d:"The Mises–Hayek theory: banks push rates down → entrepreneurs mistake it for more saving → over-investment upstream → not enough resources to finish everything → liquidation. The boom is the disease; the bust is the cure."} },
  { zh:{n:["错误投资"],d:"不是“投多了”，而是“投错了地方”：被虚假利率信号引到消费者其实不愿等待的长期项目上——回收不了的资本就是真实的社会损失。"},
    en:{n:["malinvestment","malinvestments"],d:"Not “too much investment” but investment in the wrong places: lured by a false rate signal into long projects consumers are not actually willing to wait for — unrecoverable capital is a real social loss."} },
  { zh:{n:["崩溃繁荣"],d:"米塞斯的术语：当公众意识到央行会无限印钞时，货币需求骤降、人人抢购实物——一场以货币彻底崩溃收场的“繁荣”。"},
    en:{n:["crack-up boom"],d:"Mises's term: when the public realizes the printing will never stop, money demand collapses and everyone buys anything real — a “boom” that ends in the currency's destruction."} },
  { zh:{n:["强制储蓄"],d:"信用扩张让新钱先流向投资者，把资源从消费者手里“抢”过来投入长期项目——不是自愿的储蓄，因此消费者迟早要把资源要回去。"},
    en:{n:["forced saving"],d:"Credit expansion routes new money to investors first, pulling resources away from consumers into long projects — not voluntary saving, so consumers eventually reclaim those resources."} },
  { zh:{n:["清算"],d:"萧条期里把错误投资的资本品重新定价、变卖、改作他用的过程——痛苦，但正是它把资源送回消费者真正想要的地方。"},
    en:{n:["liquidation"],d:"The bust-phase process of repricing, selling off and redeploying malinvested capital — painful, but exactly what steers resources back to where consumers actually want them."} },

  // —— 企业家与市场过程 ——
  { zh:{n:["企业家精神"],d:"在不确定性下发现并利用别人还没看到的机会——不是一种职业，而是所有行动里“向前看”的那一面。"},
    en:{n:["entrepreneurship","entrepreneurial"],d:"Discovering and acting on opportunities others have not yet seen, under uncertainty — not a profession but the forward-looking element in every action."} },
  { zh:{n:["警觉"],d:"柯兹纳的核心词：企业家的本质是“注意到”被忽视的获利机会——同样的信息在眼前，有人看见，有人没有。"},
    en:{n:["alertness","entrepreneurial alertness"],d:"Kirzner's key term: the essence of entrepreneurship is noticing an overlooked profit opportunity — the same information sits in front of everyone, and some see it while others do not."} },
  { zh:{n:["判断"],d:"米塞斯–奈特–福斯/克莱因的传统：企业家的核心工作是在无法计算概率的不确定性下，押上自己的资源做决定——这一步无法外包给算法。"},
    en:{n:["entrepreneurial judgment","judgment"],d:"The Mises–Knight–Foss/Klein tradition: the entrepreneur's core task is to commit their own resources under uncertainty with no computable odds — a step that cannot be outsourced to an algorithm."} },
  { zh:{n:["市场过程"],d:"奥派看市场不是一张均衡快照，而是一部电影：无数人不断试错、调整、模仿、淘汰，价格与计划在其中持续被修正。"},
    en:{n:["market process"],d:"Austrians see the market not as an equilibrium snapshot but as a film: countless people trying, adjusting, imitating and failing, with prices and plans continuously revised."} },
  { zh:{n:["发现程序"],d:"哈耶克的定义：竞争的价值在于它能发现“如果没有竞争没人知道”的东西——谁最便宜、什么最受欢迎、哪条路走得通。"},
    en:{n:["discovery procedure","competition as a discovery procedure"],d:"Hayek's definition: competition is valuable because it discovers what nobody could know without it — who is cheapest, what is wanted, which path works."} },
  { zh:{n:["创造性破坏"],d:"熊彼特的名词：新产品、新方法不断摧毁旧结构——市场繁荣的常态就是持续的自我拆迁，保护旧结构等于阻止进步。"},
    en:{n:["creative destruction"],d:"Schumpeter's phrase: new products and methods continually demolish old structures — a healthy market is perpetual self-demolition, and protecting the old means blocking progress."} },
  { zh:{n:["经济计算"],d:"用货币价格把异质的投入与产出折算成可比的数字，从而判断一项生产是创造还是浪费——没有市场价格就做不到，这是米塞斯 1920 年的核心论证。"},
    en:{n:["economic calculation"],d:"Using money prices to reduce heterogeneous inputs and outputs to comparable numbers, so you can tell whether a production plan creates or destroys value — impossible without market prices; Mises's core 1920 argument."} },
  { zh:{n:["知识问题"],d:"哈耶克的论证：经济所需的知识是分散的、局部的、常常说不出口的（“此时此地的知识”），任何中央机构都不可能把它收集起来。"},
    en:{n:["knowledge problem"],d:"Hayek's argument: the knowledge an economy runs on is dispersed, local and often tacit (“knowledge of the particular circumstances of time and place”) — no central body can ever gather it."} },
  { zh:{n:["默会知识"],d:"你会但说不出来的知识——骑车、看人、判断行情。它无法写进数据库，这就是为什么价格与市场不可被“计算”取代。"},
    en:{n:["tacit knowledge"],d:"What you know but cannot articulate — riding a bike, reading a person, sensing a market. It cannot be entered into a database, which is why prices and markets cannot be replaced by computation."} },
  { zh:{n:["自发秩序"],d:"没有人设计、却从无数人各自行动中长出来的秩序——语言、法律、货币、市场、互联网协议都是。哈耶克叫它 cosmos，与设计出来的 taxis 相对。"},
    en:{n:["spontaneous order"],d:"Order nobody designed that grows out of countless separate actions — language, law, money, markets, internet protocols. Hayek called it cosmos, as opposed to designed taxis."} },
  { zh:{n:["计算争论","社会主义计算争论"],d:"1920–40 年代米塞斯、哈耶克与兰格、勒纳之间关于“社会主义能否理性配置资源”的论战——奥派的答案：没有私有产权就没有价格，没有价格就没有计算。"},
    en:{n:["socialist calculation debate","calculation debate"],d:"The 1920s–40s clash between Mises/Hayek and Lange/Lerner over whether socialism can allocate rationally — the Austrian answer: no private property, no prices; no prices, no calculation."} },

  // —— 干预与制度 ——
  { zh:{n:["干预主义"],d:"米塞斯的分类：既不是社会主义也不是自由市场，而是政府用具体命令修改市场结果——每次干预都制造新问题，逼出下一次干预。"},
    en:{n:["interventionism"],d:"Mises's category: neither socialism nor free market but the state altering market outcomes by specific decree — each intervention creates new problems that call for the next."} },
  { zh:{n:["价格管制"],d:"政府规定某物不能高于（限价）或低于（最低价）某个价格——限价造成短缺，最低价造成过剩，两者都摧毁价格本该传递的信息。"},
    en:{n:["price control","price controls","price ceiling","price floor"],d:"The state decreeing a good may not sell above (ceiling) or below (floor) some price — ceilings create shortages, floors create surpluses, and both destroy the information the price was carrying."} },
  { zh:{n:["监管俘获"],d:"被监管的行业最终控制了监管者——因为它们最有动力、最有资源去影响规则，而分散的消费者没有。"},
    en:{n:["regulatory capture"],d:"The regulated industry ends up controlling the regulator — because it has the most motive and resources to shape the rules, while dispersed consumers have none."} },
  { zh:{n:["寻租"],d:"花资源去争取政府赐予的特权（牌照、补贴、关税）而非去创造价值——对个人理性，对社会纯粹浪费。"},
    en:{n:["rent-seeking","rent seeking"],d:"Spending resources to win state-granted privileges (licenses, subsidies, tariffs) instead of creating value — rational for the seeker, pure waste for society."} },
  { zh:{n:["公共选择"],d:"把经济学的自利假设用到政客和官僚身上：他们和商人一样追求自己的目标，“公共利益”不是政府行为的默认解释。"},
    en:{n:["public choice"],d:"Applying economics' self-interest assumption to politicians and bureaucrats: they pursue their own goals like anyone else, so “the public interest” is not the default explanation of state behavior."} },
  { zh:{n:["外部性"],d:"一个行动对旁人造成的未经交易的收益或成本（污染、灯塔）。主流认为它证明市场失灵；奥派追问：是产权没界定清楚，还是根本无法比较主观成本？"},
    en:{n:["externality","externalities"],d:"An untraded benefit or cost an action imposes on bystanders (pollution, lighthouses). The mainstream sees market failure; Austrians ask whether property rights are just ill-defined — and whether subjective costs can be compared at all."} },
  { zh:{n:["自由银行"],d:"没有央行、没有法定货币垄断的银行制度：任何银行都可以发行自己的纸币，靠信誉与兑付竞争——奥派内部对它是否应允许部分准备金争论激烈。"},
    en:{n:["free banking"],d:"Banking with no central bank and no legal-tender monopoly: any bank may issue its own notes and compete on reputation and redemption — Austrians argue fiercely over whether fractional reserves should be allowed within it."} },
  { zh:{n:["货币竞争"],d:"哈耶克 1976 年的提议：让私人机构发行互相竞争的货币，购买力最稳定的胜出——稳定币与比特币的出现让这个思想实验变成了现实。"},
    en:{n:["currency competition","denationalisation of money","denationalization of money"],d:"Hayek's 1976 proposal: let private issuers offer competing currencies and let the most stable purchasing power win — stablecoins and Bitcoin have turned the thought experiment into reality."} },
  { zh:{n:["先占原则"],d:"无主资源归第一个把它投入使用的人所有——洛克到罗斯巴德的产权起源理论，也是判断“谁对谁施加了外部性”的基准。"},
    en:{n:["homesteading","first-use principle","original appropriation"],d:"An unowned resource belongs to the first person who puts it to use — the Locke-to-Rothbard theory of how property begins, and the baseline for judging who is imposing on whom."} },

  // —— 宏观与学派 ——
  { zh:{n:["总量","总量分析"],d:"GDP、CPI、总投资这类把无数异质的东西加成一个数的统计——奥派的警告：加总抹掉了正是最要紧的结构信息。"},
    en:{n:["aggregates","aggregate"],d:"Statistics like GDP, CPI or total investment that add heterogeneous things into one number — the Austrian warning: the sum erases exactly the structural information that matters."} },
  { zh:{n:["凯恩斯主义"],d:"以“总需求不足导致萧条、政府支出可以补上”为核心的学派——奥派的回应：萧条是结构错配不是需求短缺，刺激只会推迟并加深清算。"},
    en:{n:["Keynesianism","Keynesian"],d:"The school built on “depressions come from deficient aggregate demand and government spending can fill the gap” — the Austrian reply: the bust is a structural mismatch, not a demand shortfall, and stimulus only delays and deepens the liquidation."} },
  { zh:{n:["货币主义"],d:"弗里德曼的学派：通胀是货币现象，央行应按固定规则稳定增加货币——与奥派同盟反凯恩斯，但在“货币中性”“央行该不该存在”上分道扬镳。"},
    en:{n:["monetarism","monetarist"],d:"Friedman's school: inflation is a monetary phenomenon and the central bank should grow money by a steady rule — allied with Austrians against Keynes, but split over money's neutrality and whether a central bank should exist at all."} },
  { zh:{n:["现代货币理论","MMT"],d:"主张主权货币国家不会破产、赤字不是约束、通胀才是唯一限制——奥派视之为坎蒂隆效应与崩溃繁荣的政策化。"},
    en:{n:["Modern Monetary Theory","MMT"],d:"Claims a sovereign issuer cannot go broke, deficits are not a constraint and only inflation limits spending — Austrians see it as Cantillon effects and the crack-up boom turned into policy."} },
  { zh:{n:["DSGE"],d:"动态随机一般均衡模型：主流宏观的标准工具，用代表性个体和均衡假设做数学模拟——奥派批评它假设掉了异质性、真实时间与不确定性。"},
    en:{n:["DSGE","DSGE model","DSGE models"],d:"Dynamic Stochastic General Equilibrium: mainstream macro's standard tool, simulating a representative agent in equilibrium — Austrians object that it assumes away heterogeneity, real time and uncertainty."} },
  { zh:{n:["劳动价值论"],d:"李嘉图与马克思的理论：商品价值由生产它所需的劳动时间决定——边际革命证明因果方向相反：是消费者的评价决定劳动值多少钱。"},
    en:{n:["labor theory of value"],d:"Ricardo's and Marx's theory that a good's value is set by the labor time it embodies — the marginal revolution showed causation runs the other way: consumers' valuations determine what labor is worth."} },
  { zh:{n:["不确定性"],d:"奈特与米塞斯意义上的“真不确定”：未来不是一副能算概率的骰子，而是尚未被创造出来的东西——这是企业家利润存在的根本原因。"},
    en:{n:["Knightian uncertainty","radical uncertainty","uncertainty"],d:"Uncertainty in Knight's and Mises's sense: the future is not a die whose odds can be computed but something not yet created — the fundamental reason entrepreneurial profit exists."} },

  // —— 新经济时代 ——
  { zh:{n:["网络效应"],d:"一件东西对你的价值随其他使用者数量上升而上升（电话、语言、货币、社交平台）——奥派会说：这正是主观价值互相依存的极端形态。"},
    en:{n:["network effect","network effects"],d:"A good becomes more valuable to you as more others use it (telephones, languages, money, social platforms) — for Austrians, the extreme case of subjective valuations depending on one another."} },
  { zh:{n:["双边市场","双边平台"],d:"同时服务两群互相需要的用户（司机与乘客、商家与买家）的平台——定价不是对每一边单独算成本，而是让整个网络转起来。"},
    en:{n:["two-sided market","two-sided markets","two-sided platform"],d:"A platform serving two groups that need each other (drivers and riders, sellers and buyers) — pricing is not cost-plus for each side but whatever makes the whole network turn."} },
  { zh:{n:["注意力经济"],d:"当信息近乎免费时，稀缺的变成了人的注意力——社交媒体的商业模式就是把注意力当作被争夺的资源来定价。"},
    en:{n:["attention economy"],d:"When information is nearly free, the scarce thing becomes human attention — social media's business model prices attention as the contested resource."} },
  { zh:{n:["反身性"],d:"索罗斯的概念：市场参与者的信念改变价格，价格又反过来改变信念——奥派视角下，这正是主观预期在市场过程里互相塑造的表现。"},
    en:{n:["reflexivity"],d:"Soros's idea: participants' beliefs move prices, and prices in turn move beliefs — through Austrian eyes, subjective expectations shaping one another inside the market process."} },
  { zh:{n:["工作量证明"],d:"比特币的共识机制：要在账本上写一页必须先烧掉真实的电力和算力——把“印钞”的成本从零变成了真实资源，这是它稀缺性的来源。"},
    en:{n:["proof of work","proof-of-work"],d:"Bitcoin's consensus rule: writing a page in the ledger requires burning real electricity and computation — turning the cost of “printing” from zero into real resources; the source of its scarcity."} },
  { zh:{n:["稳定币"],d:"锚定法币（多为美元）的链上代币，用链下储备支撑——本质上是哈耶克“私人发行竞争货币”的第一次大规模实验。"},
    en:{n:["stablecoin","stablecoins"],d:"An on-chain token pegged to a fiat currency (usually the dollar) and backed by off-chain reserves — in effect the first large-scale experiment in Hayek's privately issued competing currencies."} },
  { zh:{n:["央行数字货币","CBDC"],d:"由中央银行直接发行的数字法币——奥派的担忧：它让政府第一次能对每一笔交易实施可编程的监控与限制。"},
    en:{n:["central bank digital currency","CBDC","CBDCs"],d:"Digital fiat issued directly by a central bank — the Austrian worry: for the first time the state could apply programmable surveillance and limits to every single transaction."} },
  { zh:{n:["智能合约"],d:"部署在区块链上、按预设规则自动执行的程序——它把“合同”的执行从法院搬进了代码，但无法替代合同背后的企业家判断。"},
    en:{n:["smart contract","smart contracts"],d:"A program on a blockchain that executes preset rules automatically — moving contract enforcement from courts into code, without replacing the entrepreneurial judgment behind the contract."} },
  { zh:{n:["大语言模型","LLM"],d:"用海量文本训练出的预测下一个词的模型——奥派的追问：它压缩的是已经被说出来的知识，而市场依赖的恰恰是还没说出来的、此时此地的知识。"},
    en:{n:["large language model","large language models","LLM","LLMs"],d:"A model trained on vast text to predict the next token — the Austrian question: it compresses knowledge already articulated, while markets run on knowledge that is not yet articulated and belongs to a particular time and place."} },
  { zh:{n:["技术性失业"],d:"机器取代工人造成的失业。奥派的回答：被释放的劳动力与资本会被企业家引向新的、此前负担不起的用途——前提是价格与工资可以自由调整。"},
    en:{n:["technological unemployment"],d:"Job loss from machines replacing workers. The Austrian reply: freed labor and capital get redirected by entrepreneurs to new, previously unaffordable uses — provided prices and wages are free to adjust."} },
  { zh:{n:["算法定价"],d:"用软件根据实时数据自动调整价格——它让价格更快反映局部知识，但当所有卖家用同一套算法时，也可能出现“没人合谋的合谋”。"},
    en:{n:["algorithmic pricing"],d:"Software adjusting prices automatically from live data — it lets prices reflect local knowledge faster, yet when every seller runs the same algorithm it can produce “collusion without colluders.”"} },

  // —— 各阶段作者补充（方法与价值） ——
  { zh:{n:["模式预测"],d:"哈耶克：对复杂现象，理论只能预测“会出现什么形态的事”（方向、序列、脆弱性），不能预测具体数值与时点。"},
    en:{n:["pattern prediction","pattern predictions"],d:"Hayek: for complex phenomena, theory predicts the shape of an outcome — direction, sequence, fragility — never its magnitude or date."} },
  { zh:{n:["方法论之争"],d:"1883–84 年门格尔与施莫勒关于经济学是演绎的理论科学还是历史归纳的论战；“奥地利学派”这个名字就来自施莫勒的讥讽。"},
    en:{n:["Methodenstreit"],d:"The 1883–84 Menger–Schmoller dispute over whether economics is a deductive theoretical science or historical induction; the school's very name began as Schmoller's sneer."} },
  { zh:{n:["价值中立"],d:"韦伯–米塞斯原则：经济学不评判目的，只研究手段能否达到目的以及还会引起什么后果。"},
    en:{n:["value-freedom","Wertfreiheit","value-free"],d:"The Weber–Mises principle: economics does not judge ends; it studies only whether means achieve them and what else they cause."} },
  { zh:{n:["展示性偏好","显示偏好"],d:"罗斯巴德：一个人的价值排序只在他的实际选择中被展示出来，且只对行动那一刻有效——口头说的不算。"},
    en:{n:["demonstrated preference"],d:"Rothbard: a person's ranking is revealed only in actual choice, and only for the moment of choice — what people say does not count."} },
  { zh:{n:["序数效用"],d:"效用只能排先后、不能测大小，所以既不能相加，也不能跨人比较——这是奥派与新古典基数效用分道的起点。"},
    en:{n:["ordinal utility"],d:"Utility can be ranked but not measured, so it can be neither summed nor compared across people — where Austrians and neoclassical cardinal utility part ways."} },
  { zh:{n:["价值归属","归属理论"],d:"门格尔–维塞尔：生产要素的价值从它帮助生产的消费品的价值向上“归属”而来——价格决定成本，不是反过来。"},
    en:{n:["imputation"],d:"Menger–Wieser: a factor's value is imputed back from the value of the consumer goods it helps make — price determines cost, not the reverse."} },
  { zh:{n:["沉没成本"],d:"已经花掉、无论现在怎么选都收不回的支出。成本在选择那一刻才存在，所以沉没成本不进入任何当下决策。"},
    en:{n:["sunk cost","sunk costs"],d:"Money already spent that no present choice can recover. Cost exists only at the moment of choice, so sunk costs enter no rational decision."} },
  { zh:{n:["代表性个体","代表性行动人"],d:"DSGE 等宏观模型用一个“家庭”代表全体，抹掉了借贷双方、异质预期与资本结构——正是奥派认为最要紧的东西。"},
    en:{n:["representative agent"],d:"The single “household” that stands for everyone in DSGE-style models, erasing borrowers vs lenders, heterogeneous expectations and capital structure — exactly what Austrians think matters."} },
  { zh:{n:["理性预期"],d:"假设行动人知道经济的真实模型、只不知道下一次随机冲击——它排除了真正的不确定性，也就排除了企业家。"},
    en:{n:["rational expectations"],d:"The assumption that agents know the true model and are ignorant only of the next random shock — which excludes genuine uncertainty, and with it the entrepreneur."} },
  { zh:{n:["钢人"],d:"把对手的论点写成他自己会签字认可的最强版本，再回应——稻草人的反面，也是这门课批评任何学派前的必做动作。"},
    en:{n:["steelman","steelmanning"],d:"Restating an opponent's position in the strongest form they would sign before replying — the opposite of a strawman, and this course's rule before criticizing any school."} },

  // —— 资本、货币、周期 ——
  { zh:{n:["原始利息"],d:"米塞斯：现在商品对未来商品的价值比率，先于任何贷款合同存在，来自时间偏好——利率的内核。"},
    en:{n:["originary interest"],d:"Mises's term for the ratio between present and future goods that arises from time preference before any loan contract — the kernel of the interest rate."} },
  { zh:{n:["生存基金"],d:"庞巴维克：事先储蓄下来、用以养活迂回生产过程中劳动者的消费品储备——没有它，长生产链无法启动。"},
    en:{n:["subsistence fund"],d:"Böhm-Bawerk: the stock of saved consumer goods that feeds workers during a roundabout production process — without it, long production chains cannot start."} },
  { zh:{n:["引致需求"],d:"高级商品的需求来自它帮助生产的低级商品的需求，一路从消费者评价归属上来。"},
    en:{n:["derived demand"],d:"Demand for a higher-order good derived from demand for what it helps produce, imputed back from consumers."} },
  { zh:{n:["节俭悖论"],d:"凯恩斯：个人多储蓄会通过总需求下降使全社会储蓄反而不增；奥派回应：储蓄是对未来商品的需求，由利率传递给生产结构。"},
    en:{n:["paradox of thrift"],d:"Keynes's claim that more individual saving lowers income and so total saving; the Austrian reply: saving is demand for future goods, signaled to the production structure by the interest rate."} },
  { zh:{n:["累积过程"],d:"维克塞尔：货币利率低于自然利率时，借贷与物价上涨不会自我纠正而持续累积——奥派周期理论的前身。"},
    en:{n:["cumulative process"],d:"Wicksell: when the money rate sits below the natural rate, lending and price rises feed on themselves — the ancestor of Austrian cycle theory."} },
  { zh:{n:["需求的双重巧合"],d:"物物交换成交的条件：我恰好有你要的，你恰好有我要的；分工越细越难满足，这就是货币被“长出来”的原因。"},
    en:{n:["double coincidence of wants"],d:"The barter condition that each party happens to want what the other has; the finer the division of labor, the rarer it is — which is why money evolves."} },
  { zh:{n:["信用媒介"],d:"米塞斯：银行发行的、超出其持有货币的钞票与存款——奥派商业周期理论真正的研究对象。"},
    en:{n:["fiduciary media"],d:"Mises: bank notes and deposits issued beyond the money the issuer actually holds — the true subject of Austrian business-cycle theory."} },
  { zh:{n:["最后贷款人"],d:"白芝浩 1873：恐慌中央行对流动性不足的银行慷慨放贷、收惩罚性利率、只收好抵押品——它既止住挤兑，也消灭了挤兑的纪律作用。"},
    en:{n:["lender of last resort"],d:"Bagehot 1873: in a panic the central bank lends freely to illiquid banks at a penalty rate on good collateral — which stops runs, and also removes the discipline runs provide."} },
  { zh:{n:["增长型通缩"],d:"萨勒诺的分类：生产率提高让同量货币买到更多商品而物价下降——繁荣的常态，与信用收缩型通缩完全不同。"},
    en:{n:["growth deflation"],d:"Salerno's taxonomy: prices falling because productivity lets the same money buy more — the normal condition of prosperity, unlike bank-credit deflation."} },
  { zh:{n:["注入点"],d:"新钱进入经济的具体位置（银行准备金 vs 家庭账户）——它决定坎蒂隆路径与哪些价格先涨：2009 年涨的是资产，2021 年涨的是 CPI。"},
    en:{n:["injection point"],d:"Where new money enters the economy (bank reserves vs household accounts) — it sets the Cantillon path and which prices move first: assets in 2009, the CPI in 2021."} },
  { zh:{n:["货币均衡"],d:"自由银行派（塞尔金）的规范：货币供给应随持币需求变化，竞争性清算会约束单家银行的扩张。"},
    en:{n:["monetary equilibrium"],d:"The free-banking norm (Selgin): the money supply should track changes in the demand to hold money, with competitive clearing disciplining any one bank's expansion."} },
  { zh:{n:["幻觉利润"],d:"米塞斯：通胀期间按历史成本折旧算出的账面利润——资本消耗被当成收入分掉了。"},
    en:{n:["illusory profit","illusory profits"],d:"Mises: book profit produced by historical-cost depreciation during inflation — capital consumption paid out as income."} },
  { zh:{n:["僵尸企业"],d:"BIS 定义：连续三年营业利润付不起利息、靠再融资活着的公司；占着资本与工人却不成长也不退出——被阻止的清算留下的残渣。"},
    en:{n:["zombie firm","zombie firms"],d:"BIS definition: a firm whose operating profit has not covered interest for three straight years and lives on refinancing — holding capital and workers while neither growing nor exiting; the residue of blocked liquidation."} },
  { zh:{n:["拨弦模型"],d:"弗里德曼的发现：衰退深度能预测随后的复苏，却预测不了此前的繁荣——对 ABCT 的一个长期经验挑战。"},
    en:{n:["plucking model"],d:"Friedman's finding that recession depth predicts the following recovery but not the preceding boom — a standing empirical challenge to ABCT."} },
  { zh:{n:["久期"],d:"一项资产的现金流按现值加权的平均到期时间；越长，估值对折现率越敏感——零利率时涨最多，利率回归时跌最狠。"},
    en:{n:["duration"],d:"The present-value-weighted average time until an asset's cash flows arrive; the longer it is, the more valuation swings with the discount rate — up most at zero rates, down hardest when they return."} },
  { zh:{n:["总产出"],d:"斯库森提出、BEA 2014 年起公布的指标：所有生产阶段销售额之和（含中间品），约为 GDP 的两倍，能显示 GDP 抵消掉的上游结构。"},
    en:{n:["Gross Output"],d:"Skousen's measure, published by the BEA since 2014: total sales at every stage including intermediate goods — roughly double GDP, and it reveals the upstream structure GDP nets out."} },
  { zh:{n:["长期停滞"],d:"萨默斯 2013 年重提的主张：人口与储蓄过剩把自然利率压到零下，低增长是结构性的；奥派回应：停滞是未清算的错误投资与金融压抑造成的。"},
    en:{n:["secular stagnation"],d:"Summers's 2013 revival of Hansen: demography and a savings glut push the natural rate below zero; the Austrian reply is that stagnation is made by unliquidated malinvestment and financial repression."} },
  { zh:{n:["永久熊"],d:"无论市场如何都预言崩盘的人——把理论给出的“方向与脆弱性”误译成了日期。奥派最常见的职业病。"},
    en:{n:["permabear","permabears"],d:"One who forecasts a crash whatever the market does — translating the theory's “direction and fragility” into a date. The school's most common occupational disease."} },

  // —— 市场过程、干预与制度 ——
  { zh:{n:["无谓损失"],d:"因干预而未发生的互利交换所损失的价值——不转移给任何人，就是纯粹消失了。"},
    en:{n:["deadweight loss"],d:"Value lost from mutually beneficial exchanges an intervention prevents — transferred to no one, simply gone."} },
  { zh:{n:["调整边际"],d:"政策封住一个变量之后，行动人还能在其上移动的所有其他变量——工时、培训、质量、排队、黑市。"},
    en:{n:["margin of adjustment","margins of adjustment"],d:"Every other variable an actor can still move once a policy pins one down — hours, training, quality, queues, black markets."} },
  { zh:{n:["理性的无知"],d:"当了解一项政策的成本超过自己一票的收益时，选民理性地选择不了解——公共选择的基石之一。"},
    en:{n:["rational ignorance"],d:"A voter's rational choice not to learn about a policy when the cost of learning exceeds the value of one vote — a cornerstone of public choice."} },
  { zh:{n:["集中收益、分散成本"],d:"小群体各得大利、大群体各损小额，所以净值为负的政策仍能通过——游说的经济学。"},
    en:{n:["concentrated benefits, dispersed costs","concentrated benefits and dispersed costs"],d:"A small group gains much each while a large group loses a little each, so negative-value policies still pass — the economics of lobbying."} },
  { zh:{n:["棘轮效应"],d:"希格斯：国家在危机中扩张，危机后只部分收缩——每一次紧急状态都留下一圈永久的权力。"},
    en:{n:["ratchet effect"],d:"Higgs: the state expands in crises and only partly contracts afterwards — each emergency leaves a permanent ring of power behind."} },
  { zh:{n:["可竞争市场"],d:"进入退出成本足够低、潜在进入者就能约束在位者定价的市场（鲍莫尔 1982）——“大”不等于能随意定价。"},
    en:{n:["contestable market","contestable markets"],d:"A market where cheap entry and exit let potential rivals discipline the incumbent's price (Baumol 1982) — being big does not mean pricing freely."} },
  { zh:{n:["进入壁垒"],d:"阻止新企业进入某行业的障碍；奥派区分自然（成本）壁垒与国家（牌照、法规）壁垒，只把后者算作垄断。"},
    en:{n:["entry barrier","entry barriers","barriers to entry"],d:"An obstacle to new firms entering an industry; Austrians distinguish natural (cost) barriers from state (license, regulation) barriers and count only the latter as monopoly."} },
  { zh:{n:["时地知识"],d:"哈耶克：只有现场当事人才掌握、一上报就过时的具体情况知识——统计与数据库装不下的那部分。"},
    en:{n:["knowledge of time and place","particular circumstances of time and place"],d:"Hayek: the concrete, perishable knowledge only the person on the spot has and that is stale as soon as reported — the part no statistic or database can hold."} },
  { zh:{n:["软预算约束"],d:"科尔奈：亏损企业总能获得救助，于是亏损不再有纪律作用——社会主义企业与僵尸企业的共同病根。"},
    en:{n:["soft budget constraint"],d:"Kornai: loss-makers are always bailed out, so losses stop disciplining — the shared disease of socialist firms and zombie firms."} },
  { zh:{n:["科斯边界"],d:"公司止于内部组织成本等于市场交易成本之处（科斯 1937）——AI 与数据会移动这条边界，但不会取消它。"},
    en:{n:["Coasean boundary","boundary of the firm"],d:"The firm stops growing where internal organization cost equals market transaction cost (Coase 1937) — AI and data move this boundary but do not abolish it."} },
  { zh:{n:["去同质化"],d:"萨勒诺 1993：米塞斯的“计算”论证与哈耶克的“知识”论证是两个不同的论证——奥派内部的一场重要争论。"},
    en:{n:["dehomogenization"],d:"Salerno 1993: Mises's calculation argument and Hayek's knowledge argument are distinct arguments — an important debate inside the school."} },
  { zh:{n:["论证伦理"],d:"霍普：论证行为本身预设自我所有权与先占原则；批评者认为推不出永久排他的外部财产权——奥派内部争议最大的命题之一。"},
    en:{n:["argumentation ethics"],d:"Hoppe's claim that arguing itself presupposes self-ownership and first use; critics deny it yields permanent exclusive property in external things — one of the school's most contested theses."} },
  { zh:{n:["大玩家"],d:"科普尔：不受市场纪律约束又足以改变结果的主体（如央行），使预期从看基本面转向猜它的动作，从众加剧。"},
    en:{n:["Big Player","Big Players"],d:"Koppl: an actor immune to market discipline yet able to change outcomes (a central bank, say), shifting expectations from fundamentals to guessing its moves and intensifying herding."} },
  { zh:{n:["万花筒社会"],d:"沙克尔/拉赫曼：预期分歧使每一次行动都重排市场的碎片——均衡趋势不能被假设，只能被观察。"},
    en:{n:["kaleidic society","kaleidic"],d:"Shackle/Lachmann: divergent expectations rearrange the market with every act — an equilibrating tendency cannot be assumed, only observed."} },

  // —— 新经济时代 ——
  { zh:{n:["多归属"],d:"用户或商户同时使用多个平台/卖家；多归属成本越低，平台市场越容易再次翻转，算法合谋也越难维持。"},
    en:{n:["multi-homing"],d:"Users or merchants patronizing several platforms or sellers at once; the cheaper it is, the more contestable a platform market and the less stable any algorithmic collusion."} },
  { zh:{n:["临界点"],d:"网络品的采用比例阈值：低于它网络萎缩，高于它自我加强——奥派视之为企业家走出来的路，而不是一个均衡点。"},
    en:{n:["tipping point"],d:"The adoption threshold below which a network withers and above which it reinforces itself — for Austrians a road walked by entrepreneurs, not an equilibrium."} },
  { zh:{n:["版本化"],d:"同一产品做出多档版本让用户按估值自我归类——零边际成本商品发现估值分布的主要手段。"},
    en:{n:["versioning"],d:"Offering tiers of one product so users sort themselves by valuation — the main way zero-marginal-cost goods discover the distribution of valuations."} },
  { zh:{n:["平台风险"],d:"建立在一家平台规则上的资本品（订阅数、算法评级）在规则变更时被重估的风险——特定资本的数字版。"},
    en:{n:["platform risk"],d:"The risk that capital built on one platform's rules (subscribers, algorithm standing) is revalued when the rules change — specific capital, digital edition."} },
  { zh:{n:["劳动总量谬误"],d:"把“工作”当成一个固定量、机器拿走一份人就少一份的错误；工作是未满足的目的，而目的没有尽头。"},
    en:{n:["lump of labor fallacy","lump-of-labor fallacy"],d:"The error of treating work as a fixed quantity that machines take from people; work is unsatisfied ends, and ends are unlimited."} },
  { zh:{n:["默契合谋"],d:"无协议、无沟通的高价协调——定价算法可能“学会”它，但没有进入壁垒时不稳定。"},
    en:{n:["tacit collusion"],d:"Coordination on high prices without any agreement or communication — pricing algorithms may “learn” it, but it is unstable without entry barriers."} },
  { zh:{n:["存量/流量比","存量流量比"],d:"现存存量与年新增供给之比；硬钱的一个描述性属性，不是定价定律。"},
    en:{n:["stock-to-flow"],d:"Existing stock over annual new supply; a descriptive property of hard money, not a pricing law."} },
  { zh:{n:["自动做市商"],d:"按写死公式（如 x·y=k）被动报价的流动性池；它不发现价格——价格由套利者从外部市场搬进来。"},
    en:{n:["automated market maker","AMM","AMMs"],d:"A liquidity pool that quotes passively by a fixed formula (like x·y=k); it does not discover prices — arbitrageurs carry them in from outside."} },
  { zh:{n:["预言机"],d:"把链外价格签名写入区块链的喂价者；代码不能生产价格，只能引用价格——计算争论在链上的回声。"},
    en:{n:["oracle","oracles"],d:"A feeder that signs off-chain prices onto a chain; code cannot produce prices, only reference them — the calculation debate's on-chain echo."} },
  { zh:{n:["再质押"],d:"托管方把客户抵押或存入的资产再次抵押或借出——2022 年加密平台倒闭潮的核心机制，也是链上的部分准备金。"},
    en:{n:["rehypothecation"],d:"A custodian re-pledging or lending out client assets — central to the 2022 crypto failures, and fractional reserve by another name."} },
];
